# Configuration for baseline model comparison
# This config makes DL models predict prices instead of log returns
# to compare fairly with baseline models

tickers: ["FPT", "HPG"]
index_symbol: "VNINDEX"
source: "VCI"

start_date: "2015-01-01"
end_date: "2025-09-28"

lookback: 60
features:
  use_market_context: true
  use_calendar: true
  use_regime_flags: true

n_splits: 3
val_size: 252
test_size: 252
min_train_size: 756

# IMPORTANT: Set predict_price to true for fair comparison with baselines
predict_price: true

models: ["tcn", "gru", "lstm"]
epochs: 50
batch_size: 256
learning_rate: 0.001
patience: 15

# TCN-specific parameters
tcn:
  filters: 64
  kernel_size: 5
  dilations: [1, 2, 4, 8]
  dropout_rate: 0.1
  use_se: true
  use_multitask: true
  loss_lambda: 0.25
  weight_decay: 1e-4

# Ensemble settings
ensemble:
  enable: true
  seeds: [42, 123, 456, 789, 999]
  voting_method: "average"

backtest:
  enable: true
  thresh: 0.0
  fee: 0.001
